In [11]:
# 1) Manuel değerleri el ile girerek 3 boyutlu bir array oluşturup bir değişkene atayın. Ardından 3 boyutlu olup olmadığına bakmak için dimension'ını kontrol edin

import numpy as np

arr_3d = np.array([[[1,2,3]]])
print(arr_3d)
arr_3d.ndim

[[[1 2 3]]]


3

In [13]:
# 2) 34, 40, 46, 52... 112 şeklinde devam eden 1 boyutlu bir array oluşturun.

import numpy as np

arr = np.arange(34,113,6)
arr

array([ 34,  40,  46,  52,  58,  64,  70,  76,  82,  88,  94, 100, 106,
       112])

In [14]:
# 3) 50-500 arasında lineer artış gösteren 91 tane tam sayıdan oluşan bir array oluşturun.(dtype'ı int olsun)

import numpy as np

arr = np.linspace(50,500,91 , dtype=int)
arr

array([ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95, 100, 105, 110,
       115, 120, 125, 130, 135, 140, 145, 150, 155, 160, 165, 170, 175,
       180, 185, 190, 195, 200, 205, 210, 215, 220, 225, 230, 235, 240,
       245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300, 305,
       310, 315, 320, 325, 330, 335, 340, 345, 350, 355, 360, 365, 370,
       375, 380, 385, 390, 395, 400, 405, 410, 415, 420, 425, 430, 435,
       440, 445, 450, 455, 460, 465, 470, 475, 480, 485, 490, 495, 500])

In [18]:
# 4) 100(10**2) ile 10000(10**5) arasında logaritmik artış gösteren 8 sayıdan oluşan bir array oluşturun.

import numpy as np

arr = np.logspace(2, 5, 8, dtype= int)
arr

array([   100,    268,    719,   1930,   5179,  13894,  37275, 100000])

In [21]:
# 5) 0-8 tam arasındaki ardışık tam sayılardan oluşan(0 ve 8 dahil toplam 9 değer) 3x3 shape'inde bir matris oluşturun.

import numpy as np

arr = np.array(range(9)).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
# 6) 6x6 formatında bir sıfır matrisi oluşturun. (dtype'ı int olsun)

import numpy as np

arr = np.zeros(36 , dtype= 'int').reshape(6, 6)
arr

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [23]:
# 7) 4x4 formatında bir bir matrisi oluşturun. (dtype'ı int olsun)

import numpy as np

arr = np.ones(16 , dtype= 'int').reshape(4, 4)
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [24]:
# 8) 8x8 formatında bir birim matris oluşturun. (Sadece sol köşegeni 1 geri kalan değerleri 0 olan matris'e birim matris deniyor.) (dtype'ı int olsun)

import numpy as np

arr = np.eye(8 , dtype = 'int')
arr

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [65]:
# 9) 5x5 formatında bir köşegen matrisi oluşturun (Sadece sol üstten sağ alta doğru olan köşegendeki değerleri 3 olsun diğer bütün değerleri 0) (Bunu henüz görmediniz ama birim matrise benziyor, sadece köşegen değerleri 1 değil 3 olacak. Bir şeyler düşünün)

import numpy as np

arr = np.diag([3,3,3,3,3])
arr

array([[3, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 3]])

In [42]:
# 10) np.random modülünden uygun fonksiyonu kullanarak 0-1 arasında toplam 6 tane değerden oluşan 1 boyutlu bir array oluşturun.

arr = np.random.rand(6)
arr

array([0.85948519, 0.94010251, 0.22263089, 0.80693914, 0.94549388,
       0.70309285])

In [50]:
# 11) np.random modülünden uygun fonksiyonu kullanarak 50-100 arasındaki(50 ve 100 dahil) tam sayılardan 10 tanesiyle oluşan (5,2) shape'inde bir array oluşturun. Ardından bu arrayin shape'ini kontrol edin.

arr = np.random.randint(50,101,10).reshape(5,2)
print(arr)
arr.shape

[[ 76  82]
 [ 66  84]
 [ 66  74]
 [ 85 100]
 [ 68  64]]


(5, 2)

In [51]:
# 12) np.random modülünden uygun fonksiyonu kullanarak 100-1000(1000 dahil değil) arasındaki tam sayılardan rastgele 50 tanesinden oluşan (2,5,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in dimension'ını(boyutunu) ve shape'ini kontrol edin.

arr = np.random.randint(100,1000,50).reshape(2,5,5)
print(arr)
print(arr.ndim)
print(arr.shape)

[[[947 169 291 471 221]
  [485 490 395 677 442]
  [387 903 771 635 524]
  [285 423 337 547 634]
  [845 196 817 893 637]]

 [[946 927 497 456 475]
  [555 269 336 695 356]
  [605 466 317 991 990]
  [627 699 813 257 499]
  [437 690 657 761 314]]]
3
(2, 5, 5)


In [52]:
# 13) np.random modülünden uygun fonksiyonu kullanarak 0-100(0 ve 100 dahil) arasındaki tam sayılardan 10 tane seçerek bir array oluşturun. Bu array'in maximum, mininmum değerlerine ve bu değerlerin indexlerine bakın.

arr = np.random.randint(0,101,10)
print(arr)
print(arr.max())
print(arr.argmax())
print(arr.min())
print(arr.argmin())

[57 10  3 93 73 55 83 79 25 54]
93
3
3
2


In [55]:
# 14) np.random modülünden uygun fonksiyonu kullanarak 300-500(300 ve 500 dahil) arasındaki tam sayılardan 20 tane seçerek (2,2,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in içindeki 20 tam sayı arasından maximum ve minimum değerleri manuel olarak tespit edin ve indexleme yaparak çekmeye çalışın.

arr = np.random.randint(300,501,20).reshape(2,2,5)
print(arr)

[[[428 482 389 378 495]
  [374 402 335 336 323]]

 [[383 427 319 339 313]
  [434 371 323 369 438]]]


In [56]:
arr[0,0,4]

495

In [57]:
arr[1,0,4]

313

In [59]:
# 15) 0-50(50 dahil) arasındaki ardışık tam sayılardan oluşan bir array oluşturun. Ardından bu arrayin 20. ve 35. indexleri arasındaki değerleri 500'e eşitleyin ve yeni oluşan array'i ekrana yazdırarak broadcasting işleminin yapılıp yapılmadığını test edin.

arr = np.array(range(51))
arr[21:35] = 500
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20, 500, 500, 500, 500, 500,
       500, 500, 500, 500, 500, 500, 500, 500, 500,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50])